// Compile-time calendar identifier index — generated by build.rs.
//
// Exposes two functions:
//   `index_of(id: &str) -> Option<u8>` — write path (INSERT/UPDATE).
//   `name_of(idx: u8) -> Option<&'static str>` — read path (SELECT).
//
// The canonical array is append-only; existing indices never change across
// builds, ensuring on-disk values remain valid after extension upgrades.

include!(concat!(env!("OUT_DIR"), "/cal_index.rs"));
